version: "3"
services:
  app:
    # ビルドコンテキストは親ディレクトリとする
    ## ビルドコンテキストが変わると Dockerfileにおける COPY, ADD コマンドや.dockerignoreファイルにおけるディレクトリ指定が変わる
    ## .dockerignore はビルドコンテキストに置く必要があることに注意
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # run -dit /bin/bash に当たるcommand記述  
    ## bashを対話モードで起動したままにしておく
    # docker-compose.yml の entrypoint, command はそれぞれ Dockerfile の ENTRYPOINT, CMD に対応する
    command: [ "/bin/bash", "-c", "exec /bin/bash" ]
    # run -dit /bin/bash の -t に当たる部分
    tty: true

    # ストレージマウント
    # ホスト側のディレクトリをコンテナ側のディレクトリにマウントする
    ## volumes というプロパティ名だが、必ずしもボリュームマウントではない
    volumes:
      # `:` を使うとバインドマウントとなる
      # docker-compose.yml内では、ホスト側のURLはビルドコンテキストではなくdocker-compose.ymlがある場所が基準となる
      - ..:/home/node/versatile
